fail_fast: true
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pipenv run pylint
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black
        types: [python]
      
      - id: add
        name: add
        stages: [commit]
        language: system
        entry: git add
        types: [python]